name: Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            lfs: true

      - name: Select Xcode 26.3
        run: sudo xcode-select -s /Applications/Xcode_26.3.app

      - name: Build and Test
        run: |
          xcodebuild test \
            -project WallaRobots.xcodeproj \
            -scheme WallaRobots \
            -destination 'platform=iOS Simulator,name=iPhone 17,OS=26.4' \
            -enableCodeCoverage YES \
            clean build test
