name: SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git safe directory
        run: git config --global --add safe.directory /github/workspace

      - name: SwiftLint Check
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          WORKING_DIRECTORY: WallaRobots
